FIELD_SYNONYMS = {
    # --- Balance Sheet ---
    "total_assets": [
        "total assets",
        "total assets, net",
        "assets total",
        "assets, total",
    ],
    "current_assets": [
        "total current assets",
        "current assets",
        "current assets, total",
    ],
    "total_liabilities": [
        "total liabilities",
        "liabilities total",
        "liabilities, total",
        "total liabilities and stockholders' equity",
    ],
    "current_liabilities": [
        "total current liabilities",
        "current liabilities",
        "current liabilities, total",
    ],
    "total_equity": [
        "total stockholders' equity",
        "total equity",
        "total shareholders' equity",
        "stockholders' equity",
        "shareholders' equity",
        "total shareholders equity",
        "total stockholders equity",
        "equity total",
    ],
    # --- Income Statement ---
    "revenue": [
        "total revenue",
        "revenue",
        "net revenue",
        "total net revenue",
        "net revenues",
        "total net revenues",
        "revenues",
        "total revenues",
        "net sales",
        "total net sales",
        "sales",
        "total sales",
    ],
    "cogs": [
        "cost of goods sold",
        "cost of revenue",
        "cost of sales",
        "cost of products sold",
        "total cost of revenue",
        "cost of goods and services sold",
    ],
    "operating_income": [
        "operating income",
        "income from operations",
        "operating income (loss)",
        "operating profit",
        "operating earnings",
    ],
    "net_income": [
        "net income",
        "net income (loss)",
        "net profit",
        "net profit (loss)",
        "net earnings",
        "net earnings (loss)",
        "profit for the year",
        "profit for the period",
        "net income attributable to",
    ],
}